name: Build - Linux

on:
  push:

jobs:
  call-workflow:
    uses: Silverlan/pragma/.github/workflows/build-module.yml@main
    if: github.repository != 'Silverlan/pr_module_template'
    with:
      repository: 'Silverlan/pr_rig'
      branch: 'main'
      os: linux
    secrets:
      repository_token: ${{ secrets.REPO_ACCESS_TOKEN }}
    permissions:
      contents: write
