name: Build - Linux

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '0 0 * * *'

jobs:
  call-workflow:
    uses: Silverlan/pragma/.github/workflows/build-module.yml@main
    if: github.repository != 'Silverlan/pr_module_template'
    with:
      repository: 'Silverlan/pr_rig'
      branch: 'main'
      pragma-branch: 'develop'
      os: linux
      tag: ${{ github.event_name == 'schedule' && 'latest' || '' }}
    secrets:
      repository_token: ${{ secrets.REPO_ACCESS_TOKEN }}
    permissions:
      contents: write
